routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\inventorycontroller;
use App\Http\Controllers\con_additem;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/','con_login');
//Route::get('/prod_history','con_prodhistory');
Route::get('/inventory', 'inventorycontroller@showInventory');
Route::resource('/admin_login','con_adminsign');
Route::resource('/store_stock','con_storeinventory');
Route::resource('/store_transactions','con_storetransactions');
Route::resource('/stores_sales','con_storeSales');
Route::resource('/additem','con_additem');
Route::resource('/purchase','con_purchase');
Route::resource('/pricelist','con_pricelist');
Route::resource('/payables','con_payables');  
Route::resource('/addTransaction','con_transactions');
Route::resource('/transProd','con_transProd');
Route::resource('/purchaseProd','con_purchaseProd');
Route::resource('/transAddProd','con_transAddProd');
Route::resource('/approval','con_approval');
Route::get('/approver','con_approver@showPOforApproval');
Route::post('/approver','con_approver@ApprovePO')->name('approver.approvePO');
Route::delete('/approver','con_approver@RejectPO')->name('approver.RejectPO');
Route::resource('/approved','con_approved');
Route::resource('/salesTransaction','con_salesTransaction');
Route::resource('/salesTransProd','con_salesTransProd');
Route::get('/viewSalesTrans','con_viewSalesTrans@showSalesTrans')->name('viewSalesTrans.view');
Route::get('/store_status','con_storeStatus@index')->name('storeStatus');
Route::resource('/signin','con_login');
Route::resource('/signout','con_signout');
Route::resource('/edit_po','con_poStatus');
Route::resource('/incomplete_po','con_incomplete');
Route::resource('/product_details','con_productDetails');

//added module for expense
Route::resource('/listExpense','con_expenselist');



//declared by Paola


Route::resource('/bucal_inventory','con_transactionsBucal');
Route::get('/bucal_storestock','inventorycontrollerBucal@showInventory');
Route::resource('/bucal_salestransaction','con_salesTransactionBucal');
Route::resource('/bucal_additem','con_additemBucal');
Route::resource('/bucal_pricelist','con_pricelistBucal');
Route::resource('/bucal_salesTransProd','con_salesTransProdBucal');
Route::resource('/bucal_transAddProd','con_transAddProdBucal');
Route::resource('/bucal_transProd','con_transProdBucal');
Route::get('/bucal_viewSalesTrans','con_viewSalesTransBucal@showSalesTrans')->name('bucal_viewSalesTrans.view');
Route::get('/bucal_viewSalesTrans','con_viewSalesTransBucal@showSalesTransTwo');
Route::resource('/bucal_addTransaction','con_transactionsBucal');

//central inventory
Route::get('/central_inventory','inventorycontrollercentral@showInventory');
Route::resource('/central_transactions','con_transactionsCentral');
Route::resource('/central_transAddProd','con_transAddProdCentral');

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Inventory extends Model
{
    protected $table='tbl_inventory';
    protected $primaryKey='ProdID';
}

app/InventoryBucal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class inventoryBucal extends Model
{
    protected $table='tbl_bucalinventory';
    protected $primaryKey='ProdID';
}

app/InventoryCentral.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class inventoryCentral extends Model
{
    protected $table='tbl_central_inventory';
    protected $primaryKey='ProdID';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/dboBucalExpense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboBucalExpense extends Model
{
    protected $table='tbl_bucalexpense';
    protected $primaryKey='ExpenseNo';
}

app/dboExpense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboExpense extends Model
{
    protected $table='tbl_expense';
    protected $primaryKey='ExpenseNo';
}

app/dboPOProdTemp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboPOProdTemp extends Model
{
    protected $table='tbl_purchaseprod_temp';
    protected $primaryKey='pProd';
}

app/dboProducts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboProducts extends Model
{
    protected $table = 'tbl_product';
    protected $primaryKey = 'ProductID';
}

app/dboProductsBucal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboProductsBucal extends Model
{
    protected $table = 'tbl_bucalproduct';
    protected $primaryKey = 'ProductID';
}

app/dboPurchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboPurchase extends Model
{
    protected $table="tbl_purchase";
    protected $primaryKey='PONumber';
}

app/dboPurchaseBucal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboPurchaseBucal extends Model
{
    protected $table="tbl_bucalpurchase";
    protected $primaryKey='PONumber';
}

app/dboPurchaseProd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboPurchaseProd extends Model
{
    protected $table='tbl_purchaseprod';
    protected $primaryKey='pProd';
}

app/dboSalesTransProd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboSalesTransProd extends Model
{
    protected $table="tbl_salesprod";
    protected $primaryKey='salesProdNo';
}

app/dboSalestrans.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboSalestrans extends Model
{
    protected $table='tbl_salestrans';
    protected $primaryKey='SalesID';
}

app/dboTimelog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboTimelog extends Model
{
    protected $table='tbl_timelog';
    protected $primaryKey='logID';
}

app/dboTimelogBucal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboTimelogBucal extends Model
{
    protected $table='tbl_bucaltimelog';
    protected $primaryKey='logID';
}

app/dboTransProd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboTransProd extends Model
{
    protected $table='tbl_transactionprod';
    protected $primaryKey='transProdNo';
}

app/dboTransactions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboTransactions extends Model
{
    protected $table="tbl_transaction";
    protected $primaryKey='transID';
}

app/dboUsers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboUsers extends Model
{
    //
}

app/dboUsersBucal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class dboUsersBucal extends Model
{
    //
}

resources/views/addExpense.blade.php
@extends('template')

@section('content')
<script>
    function discountCompute()
    {
        var price=document.getElementsByName('tb_regularPrice')[0].value;

        var discounted=price - (price*.20);
        document.getElementsByName('tb_discountedPrice')[0].value=discounted.toString();
    }
</script>
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-6'>
       
        @if(strcmp(session('UserType'),'Bucal')!=0)
            <form method='POST'url="/additems"action="{{ route('additem.store') }}"id="SaveItem">
              
        @endif
        @if(strcmp(session('UserType'),'Bucal')==0)
            <form method='POST'url="/additems"action="{{ route('bucal_additem.store') }}"id="SaveItem">  
        @endif
        
            <div class='card-header'>
                <h3 class='card-title'>Add a Product</h3>
            </div>           
               @csrf
                
            
            <div class='card-footer'>
                <div class='row'>
                    <div class='col-md-3'><input type='submit'name='btn_submit'value='Submit Product'class='btn btn-primary'></div>
                   
                    
                </div>
        </form>  
            </div>
        </div>
        <div class='col-md-6'>
            <div class='card-header'>
                <h3 class='card-title'>Product List</h3>
            </div>         
            <div class='card-body'>
            <div class='card-body table-responsive p-0'>
                        <table class="table table-head-fixed dataTable">
                            <thead>
                                <tr>
                                    <th>Product ID</th>
                                    <th>Product Name</th>
                                    <th>Regular Price</th>
                                    <th>Discounted Price</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                           
                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->ProdCode}}</td>
                                    <td>{{$product->ProdName}}</td>
                                    <td>{{$product->Regprice}}</td>
                                    <td>{{$product->DiscPrice}}</td>                                   
                                    <td>

                                    @if(strcmp(session('UserType'),'Bucal')!=0)
                                        <form method="POST"action="{{url('additem',$product->ProductID)}}">
              
                                    @endif
                                    @if(strcmp(session('UserType'),'Bucal')==0)
                                        <form method="POST"action="{{url('bucal_additem',$product->ProductID)}}">  
                                    @endif
                                    

                                    @method('DELETE')
                                    @csrf
                                    <button type='submit'name='btn_delete'class='btn btn-primary'>Delete</button></td>
                                    </form>
                                </tr>
                            @endforeach
                            </tbody>
                            
                    </table>  
                </div>       
            </div>
            <div class='card-footer'>
            </div>
        </div>
    </div>   
</div>

@endsection

resources/views/additem.blade.php
@extends('template')

@section('content')
<script>
    function discountCompute()
    {
        var price=document.getElementsByName('tb_regularPrice')[0].value;

        var discounted=price - (price*.20);
        document.getElementsByName('tb_discountedPrice')[0].value=discounted.toString();
    }
</script>
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-6'>
       
        @if(strcmp(session('UserType'),'Bucal')!=0)
            <form method='POST'url="/additems"action="{{ route('additem.store') }}"id="SaveItem">
              
        @endif
        @if(strcmp(session('UserType'),'Bucal')==0)
            <form method='POST'url="/additems"action="{{ route('bucal_additem.store') }}"id="SaveItem">  
        @endif
        
            <div class='card-header'>
                <h3 class='card-title'>Add a Product</h3>
            </div>           
               @csrf
                <div class='card-body'>
                    <div class='form-group'>
                        <div class='row'>
                            <div class='col-md-6'>
                            <label for='tb_prodID'>Product Catalog</label><label style='color:red'>*</label>
                            <input type='text'name='tb_prodID'placeholder='Product Catalog No.'class='form-control'>
                            </div>
                        </div>
                        <label for='tb_prodDesc'>Product Name</label><label style='color:red'>*</label>
                        <input type='text'name='tb_prodDesc'placeholder='Product Name'class='form-control'>
                        <label for='tb_supplier'>Supplier</label><label style='color:red'>*</label>
                        <input type='text'name='tb_supplier'placeholder='Supplier Name'class='form-control'>
                                    
                        <div class='col-md-6'>   
                            <label for='tb_unit'>Unit</label><label style='color:red'>*</label>                        
                            <input type='text'name='tb_unit'placeholder='Unit of Measurement'class='form-control'>
                        </div>
                        <div class='row'> 
                            <div class='col-md-6'>
                                <label for='tb_regularPrice'>Regular Price</label><label style='color:red'>*</label>
                                <input type='text'name='tb_regularPrice'onchange='return discountCompute();'placeholder='0'class='form-control'>
                            </div>
                            <div class='col-md-6'>
                                <label for='tb_discountedPrice'>Discounted Price</label>
                                <input type='text'name='tb_discountedPrice'placeholder='0'class='form-control'>
                            </div>
                        </div>
                        <div class='col-md-6'>    
                        <label for='btn_submitTrans' style='color:red'>All fields marked with an asterisk (*) are required.</label>
                        </div>
                    </div>
                </div>
            
            <div class='card-footer'>
                <div class='row'>
                    <div class='col-md-3'><input type='submit'name='btn_submit'value='Submit Product'class='btn btn-primary'></div>
                   
                    
                </div>
        </form>  
            </div>
        </div>
        <div class='col-md-6'>
            <div class='card-header'>
                <h3 class='card-title'>Product List</h3>
            </div>         
            <div class='card-body'>
            <div class='card-body table-responsive p-0'>
                        <table class="table table-head-fixed dataTable">
                            <thead>
                                <tr>
                                    <th>Product ID</th>
                                    <th>Product Name</th>
                                    <th>Regular Price</th>
                                    <th>Discounted Price</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                           
                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->ProdCode}}</td>
                                    <td>{{$product->ProdName}}</td>
                                    <td>{{$product->Regprice}}</td>
                                    <td>{{$product->DiscPrice}}</td>                                   
                                    <td>

                                    @if(strcmp(session('UserType'),'Bucal')!=0)
                                        <form method="POST"action="{{url('additem',$product->ProductID)}}">
              
                                    @endif
                                    @if(strcmp(session('UserType'),'Bucal')==0)
                                        <form method="POST"action="{{url('bucal_additem',$product->ProductID)}}">  
                                    @endif
                                    

                                    @method('DELETE')
                                    @csrf
                                    <button type='submit'name='btn_delete'class='btn btn-primary'>Delete</button></td>
                                    </form>
                                </tr>
                            @endforeach
                            </tbody>
                            
                    </table>  
                </div>       
            </div>
            <div class='card-footer'>
            </div>
        </div>
    </div>   
</div>

@endsection

resources/views/admin_signin.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{asset('login/fonts/icomoon/style.css')}}">

    <link rel="stylesheet" href="{{asset('login/css/owl.carousel.min.css')}}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('login/css/bootstrap.min.css')}}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{{asset('login/css/style.css')}}">

    <title>VERA POS</title>
    <style>

        
    </style>
  </head>
  <body>
  

  <div class="d-lg-flex half">
  <div class="bg" style="background-image:url({{asset('login/images/background.PNG')}});"></div>
    <div class="contents order-2 order-md-1">
    

    <div class="container">
        <div class="row align-items-center justify-content-center" style='background-color:rgb(44,78,140)'>
        <img src="login/images/veraposlogo2.png" width="800px">
          <div class="col-md-7">
            <div class="mb-4">
              <h3 style='color:white'>Sign In as Administrator</h3>
              <p class="mb-4">Welcome to VERA POS Hub</p>
            </div>
            
     
            <form action="/admin_login" method="POST"action="{{route('admin_login.store')}}"> 
              

   
            @csrf
              
              <div class="form-group mb-3" style="border:none">

              
              <div class="form-group mb-3" style="border:none">
                <input type="text" class="form-control" name="tb_username"placeholder='  Name'>

              </div>
              
              <div class="form-group mb-3" style="border:none">
                <input type="password" class="form-control" name="tb_password"placeholder='  Password'>
                
              </div>
        
         

              <input type="submit" value="Log In" class="btn btn-block btn-primary" style='background-color:rgb(146,208,80); color:rgb(44,78,140)'>
            </form>
            <br>
            <div>
            @if($Error=="1")
            <div class='alert alert-danger alert-dismissible'>
                Wrong Username or Password
              </div>
            @endif
            @if($Error=="2")
            
              <div class='alert alert-danger alert-dismissible'>
                Account not registered as admin
              </div>
            @endif
              Not an admin?<a href='signin'>Click here to sign in as employeee</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    
  </div>
    
    

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
  </body>
</html>

resources/views/approval.blade.php
@extends('template')

@section('content')
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-12'>
            <div class='card-header'>
                <h2 class='card-title'>Payables</h2>
            </div>
            <div class='card-body'>
                <table class="table table-head-fixed">
                    <thead>
                        <tr>
                            <th>Purchase #</th>
                            <th>Date</th>
                            <th>Supplier</th>
                            <th>Payment Terms</th>
                            <th>Vatable Sales</th>
                            <th>Total Sales</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($deliveredPOs as $deliveredPO)
                        <tr>
                            <td>{{$deliveredPO->PONumber}}</td>
                            <td>{{$deliveredPO->podate}}</td>
                            <td>{{$deliveredPO->Supplier}}</td>
                            <td>{{$deliveredPO->Terms}}</td>
                            <td>{{$deliveredPO->Vatable}}</td>
                            <td>{{$deliveredPO->TotalSales}}</td>
                            <td>
                                <form method='GET'url='/approver'action="{{route('approval.edit',$deliveredPO->PONumber)}}">
                                  @csrf
                                 
                                    <input type='submit'value='View PO'>

                                </form>
                            </td>
                            
                        </tr>
                    @endforeach
                    </tbody>
                    
                    
                </table>
                <table>
                   
                </table>
            </div>
            <div class='card-footer'>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transProd.blade.php
@extends('template')

@section('content')
<div class='container-fluid'>

        @if(strcmp(session('UserType'),'Bucal')!=0))
            <form method='POST'url='/transProd'action="{{route('transProd.store')}}">
              
        @endif
        @if(strcmp(session('UserType'),'Bucal')==0)
        <form method='POST'url='/bucal_transProd'action="{{route('bucal_transProd.store')}}"> 
        @endif


    @csrf
    <div class='col-md-6'id='popout-modal'>
            <div class='modal-content'style='margin:auto auto;position:relative;'>
                <div class='modal-header'>Please fill the following information</div>
                <div class='modal-body'>
                    <div class='form-group'>
                        
                            <label for='tb_prodId'>Product Catalog</label>
                            <input type='text'name='tb_prodId'class='form-control'>
                            <label for='tb_prodDesc'>Product Description</label>
                            <input type='hidden'name='tb_availQuantity'>
                            <input type='text'name='tb_prodDesc'class='form-control'>
                            <label for='tb_Expiry'>Expiration</label>
                            <input type='text'name='tb_Expiry'class='form-control'>
                            <label for='tb_lot'>Lot Number</label>
                            <input type='text'name='tb_lot'class='form-control'>
                            <label for='tb_quantity'>Quantity</label>
                            <input type='text'name='tb_quantity'class='form-control'placeholder='please put number below available quantity for out transactions'>
                            <label for='tb_unit'>Unit</label>
                            <input type='text'name='tb_unit'class='form-control'placeholder='Unit'>
                            <label for='btn_addProduct'>Please fill all fields before submitting</label>
                            <button type='submit'name='btn_addProduct'class='form-control btn btn-primary'>Add Product</button>
                        
                    </div>
                </div>
                <div class='modal-footer'></div>
            </div>
            
    </div>
    <div class='row'>
        <div class='col-md-12'>
            <div class='card-header'>
                <h2 class='card-title'>Add Product to Transaction</h2>
                
           
            </div>
            
          
           
            <div class='card-body'>
          
                
                @foreach($transDetail as $transactDetails)          
                    
                    <div class='form-group'>
                        
                        <label for='tb_transID'>Transaction ID</label>
                        <input type='text'name='tb_transID'value='{{$transactDetails->transID}}'>
                        <label for='tb_transType'>Type</label>
                        <input type='text'name='tb_transType'value='{{$transactDetails->transType}}'>
                        <label for='tb_person'>Person Assigned</label>
                        <input type='text'name='tb_person'value='{{$transactDetails->careTo}}'>
                        <label for='tb_date'>Date of Transaction</label>
                        <input type='text'name='tb_date'value='{{$transactDetails->created_at}}'>
                        <a href="/addTransaction"class='btn btn-primary'>Finish</a>
                       

                    </div>  

                 @endforeach
    </form>
                <div class='col-md-12'id='div_addedProd'style='overflow:scroll;height:300px;max-height:300px;'>
                    Added Products
                
                    <table class="table table-head-fixed">
                    <thead>
                        <th>Product Code</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Remove Product</th>
                    </thead>
                    <tbody>
                        @foreach($addedProducts as $addedProduct)
                        <tr>
                            <td>{{$addedProduct->prodId}}</td>
                            <td>{{$addedProduct->prodDesc}}</td>
                            <td>{{$addedProduct->quantity}}</td>
                            <td>
                            @if(strcmp(session('UserType'),'Bucal')!=0)
                                <form method='POST'action="{{url('transProd',$addedProduct->transProdNo)}}">
                                
                            @endif
                            @if(strcmp(session('UserType'),'Bucal')==0)
                                <form method='POST'action="{{url('bucal_transProd',$addedProduct->transProdNo)}}">
                            @endif
                            
                            @method('DELETE')
                            @csrf
                            
                           
                        
                            <input type='hidden'name='tb_aProdQuantity'value='{{$addedProduct->quantity}}'>
                            <button type='submit'name='btn_remove'class='btn btn-primary'value="{{$addedProduct->prodId}}">Remove Product</button> 
                            </form>            
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
                <div class='col-md-12'id='div_availProd'>
                        Available Products
                        <table class="table table-head-fixed"style="max-height:500px;">
                            <thead>
                                <tr>
                                    <th>ProdID</th>
                                    <th>ProdDesc</th>
                                    <th>Available Quantity</th>
                                    <th>Unit</th>
                                    <th>Lot Number</th>
                                    <th>Expiry</th>
                                    
                                </tr>
                            </thead>
                        
                            
                            <tbody>
                                @foreach($availableProducts as $availableProd)
                                    <tr>        
                                        <td>{{$availableProd->ProdCat}}</td>
                                        <td>{{$availableProd->ProdDesc}}</td>
                                        <td>{{$availableProd->Quantity}}</td>
                                        <td>{{$availableProd->Unit}}</td>
                                        <td>{{$availableProd->lot}}</td>
                                        <td>{{$availableProd->Expiry}}</td>
                                        <td><button type='button'name='btn_add'value='{{$availableProd->ProdCat}}*{{$availableProd->ProdID}}*{{$availableProd->ProdDesc}}*{{$availableProd->Quantity}}*{{$availableProd->Unit}}*{{$availableProd->Category}}*{{$availableProd->Expiry}}*{{$availableProd->lot}}'onclick="return transQuantity(this.value);">Add</button></td>
                                        
                                    </tr>
                                @endforeach
                                <script>
                                function transQuantity(clicked)
                                    {
                                        document.getElementById("popout-modal").style.display="block";
                                        document.getElementById("div_availProd").style.display="none";
                                        document.getElementById("div_addedProd").style.display="none";
                                        document.getElementById("popout-modal").style.display="block";
                                        var buttondetails=clicked.split("*");
                                    
                                        document.getElementsByName("tb_prodId")[0].value=buttondetails[0];
                                        document.getElementsByName('tb_prodDesc')[0].value=buttondetails[2].toString();
                                        document.getElementsByName('tb_quantity')[0].value=buttondetails[3].toString();
                                        document.getElementsByName('tb_unit')[0].value=buttondetails[4].toString();
                                        document.getElementsByName('btn_addProduct')[0].value=buttondetails[1].toString();
                                        document.getElementsByName('tb_availQuantity')[0].value=buttondetails[3].toString();
                                        document.getElementsByName('tb_Expiry')[0].value=buttondetails[6].toString();
                                        document.getElementsByName('tb_lot')[0].value=buttondetails[7].toString();
                                         
                                        
                                    }
                                
                                </script>  
                            </tbody>
                        </table>
                </div>
            </div>
            <div class='card-footer'>
            </div>
        </div>
    </div>
</div>
@endsection